### PR TITLE
Adding libao audio bindings & Term colors shard

### PR DESCRIPTION
**Pull request by megatux**

### CODE REVIEW

**Comment by straight-shoota** [comment]
Sorry, the format spec is a bit pedantic. Can you apply the requested change?

**Comment by straight-shoota** [comment]
Now this removes `mjago/sonicri`. Is that on purpose?

**Comment by megatux** [comment]
> Now this removes `mjago/sonicri`. Is that on purpose?

:facepalm: ugh, sorry. Will try not to do 2 things at the same time :grimacing:

**Comment by straight-shoota** [comment]
Thanks!

**Pull request merged**
