### PR TITLE
Update cadmium location and description

### PR DESCRIPTION
**Pull request by watzon**

### CODE REVIEW

**Comment by watzon** [comment]
@straight-shoota done :+1:

**Comment by straight-shoota** [comment]
Now the issue is that watzon/cadmium is also listed in `Machine_Learning.yml`. This needs to be updated to the new location as well. Or maybe just remove it, I'm not sure if it fits into that category?

**Comment by watzon** [comment]
Tbh Machine Learning and Natural Language can probably be merged under the ML umbrella. NLP is just a subset of ML.

**Comment by straight-shoota** [comment]
No, most of the shards in that category have nothing to do with ML. It's more like i18n etc.

**Comment by watzon** [comment]
I guess it would make sense to have it in both then

**Pull request closed without merging**
